### ISSUE TITLE
can i join i still wand to help

### ISSUE THREAD

**Issue by Wesley-Van-Neck** [BlueLightJapan/BlueLightAPP#2]
btw my old acound is caspervanneck (wesleyvanneck) i still wand to help @haniokasai @kametan0730MC @fuyutsuki

**Comment by Wesley-Van-Neck** [comment]
you can trust me

**Comment by Wesley-Van-Neck** [comment]
): i tink i shult stop dreaming

**Comment by ghost** [comment]
Would you please wait until the preparation is over because I'd like to prepare for the release of BlueLight?

**Comment by Wesley-Van-Neck** [comment]
@fuyutsuki yea uhm yes ):

**Comment by Wesley-Van-Neck** [comment]
@fuyutsuki what do tink of me? am a noob or somting else

**Comment by ghost** [comment]
@Asuna-Yuuki I trust you, but I am not a leader so I can not decide whether to give authority...
